from . import curso 
from . import student
from . import apoderado
from . import aula
from . import materia 
from . import nota 
from . import boletin 
from . import libreta 
from . import inscripcion 
from . import curso_materia
from . import hr_employee
from . import mensualidad
from . import report_payment
from . import notice
from . import res_users
from . import lista_asistencia
from . import asistencia_rel